language: ruby
sudo: false

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - rvm: 2.2.4
      gemfile: gemfiles/opal_0.10.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/opal_0.9.gemfile

before_install:
  - git submodule update --init

before_script:
  - "bundle exec ruby util/git_modules.rb"

script:
  - "bundle exec rake"
