language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - node_modules

matrix:
  fast_finish: true

  include:
    - rvm: 2.2.4
      gemfile: gemfiles/opal_0.10.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/opal_0.9.gemfile

before_install:
  - git submodule update --init
  # New ppal-rspec needs new Phantom that Travis doesn't have
  - npm install phantomjs-prebuilt
  - "export PATH=`pwd`/node_modules/phantomjs-prebuilt/bin:$PATH"
  - phantomjs -v

before_script:
  - "bundle exec ruby util/git_modules.rb"

script:
  - "bundle exec rake"
