language: ruby
sudo: false

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - rvm: 2.1.0
    - rvm: 2.2.3
    - rvm: 2.2.4
    - rvm: 2.2.4
      gemfile: gemfiles/opal_master.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/opal-0.8.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/opal-0.9-stable.gemfile

  allow_failures:
    - gemfile: gemfiles/opal_master.gemfile

before_install:
  - git submodule update --init

script:
  - "bundle exec rake"
